name: Deploy shahs-cms to Lightsail

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build & Deploy to Lightsail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Write the private key to a file and lock permissions
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      # Upload build to server (rsync over ssh with our key file)
      - name: Deploy files to Lightsail
        run: |
          rsync -avz --delete \
            -e "ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" \
            dist/ ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIR }}/dist/

      # Restart Apache
      - name: Restart Apache
        run: |
          ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.HOST }} \
            'sudo /opt/bitnami/ctlscript.sh restart apache'
